# Generated by Django 3.1.7 on 2021-11-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskdesc',
            field=models.TextField(verbose_name=0),
        ),
    ]
